### ISSUE TITLE
Double icons

### ISSUE THREAD

**Issue by lombardi-gux** [ikenfin/Sublime-Numix-light-theme#1]
I tried installing it into S3, 3083 on Mac 10.10.3 and restarted S3.  Got double sidebar icons:

![screen shot 2015-04-14 at 8 53 05 am](https://cloud.githubusercontent.com/assets/7459986/7136992/ebc246e6-e283-11e4-82db-9acdcb663a87.png)

**Comment by ikenfin** [comment]
Fixed, thanks!
