### ISSUE TITLE
Sidebar icons support

### ISSUE THREAD

**Issue by gj1118** [ikenfin/Sublime-Numix-light-theme#2]
This looks nice, but can you please support the sidebar icons ?  

thanks

**Comment by ikenfin** [comment]
Hi! I fixed duplicate sidebar icons on last commit. Thanks for feedback!

**Comment by gj1118** [comment]
i dont think this was related to the issue that i raised. Sublime Text supports sidebar icons . I was wondering if this theme would support that...

**Comment by ikenfin** [comment]
Sorry, i think, due sleepless night i didnt understand your message correctly. I will add support for sidebar icons asap.

**Comment by ikenfin** [comment]
Hello, i have good news - now theme is support ST3 sidebar icons!
