### ISSUE TITLE
Tab height

### ISSUE THREAD

**Issue by gj1118** [ikenfin/Sublime-Numix-light-theme#3]
Hi , I am using your theme . Its very pleasant on the eyes. However is there a way I can set the tab height ?  

thanks 

With Regards
Gagan Janjua

**Comment by ikenfin** [comment]
Hi, i think this would be cool! 
I'll do my best to implement this feature asap!

Thanks!

**Comment by ikenfin** [comment]
Unfortunately it was not as easy as I thought. :(
However, i added two options to configure tab height with fixed values:
`numix_light_tabs_med` and `numix_light_tabs_big` (see README for details).

You can also use this answer from StackOverflow http://stackoverflow.com/a/22726599 and manually set tab_height [option](https://github.com/ikenfin/Sublime-Numix-light-theme/blob/master/Numix%20Light.sublime-theme#L21).

**Comment by gj1118** [comment]
That was helpful. Thanks for the help. But while we are on this topic , can you also please introduce another setting for tab_height_small : 24 pixels as well ?  

I have a small mac monitor and i dont want to loose space in the tabs. 24 pixels should serve me fine. 

thanks

**Comment by ikenfin** [comment]
Sure, option called `numix_light_tabs_small`, added in 1.0.6.
