### ISSUE TITLE
Code Folding Chevrons are not visible

### ISSUE THREAD

**Issue by gj1118** [ikenfin/Sublime-Numix-light-theme#4]
Hi , 
I am using solarized light color scheme with Numix light scheme. I have found out that whenever I am using a light colored scheme , the code folding chevrons are not visible. 

![image](https://cloud.githubusercontent.com/assets/473101/7277174/769bba6e-e8dc-11e4-8044-c5a8393934b2.png)

Can you please take a look at this ? 

Thanks

**Comment by ikenfin** [comment]
Hi! Fixed, thanks!

**Comment by gj1118** [comment]
yup this is fixed .. thanks
