### ISSUE TITLE
Laravel blade icon is not present

### ISSUE THREAD

**Issue by gj1118** [ikenfin/Sublime-Numix-light-theme#5]
Hi , 
I am a laravel developer. In the sidebar laravel blade icon is not appearing when the file type is blade. 

![image](https://cloud.githubusercontent.com/assets/473101/7277239/ec4065d0-e8dc-11e4-8ad0-90715516fee1.png)

Can you please take a look at this ? If you cannot find a laravel blade icon , can you please use the same icon as the PHP icon ? Some icon is better than no icon - I would think . 

Thanks and Regards
Gagan Janjua

**Comment by ikenfin** [comment]
Hi! Thanks for your interest and sorry for long delay - too busy now:(
I updated theme (v1.0.4) and added *tmPreferences files from SetiUI Icons repo.

![ttt](https://cloud.githubusercontent.com/assets/1705564/7368999/8c1f4548-edb6-11e4-8303-710cbb8c4c86.png)
