### ISSUE TITLE
Scrollbars on mac os do not render properly

### ISSUE THREAD

**Issue by gj1118** [ikenfin/Sublime-Numix-light-theme#6]
The vertical and the horizontal scrollbars do no render properly on MAC X Yosemite (10.10.3). 

![image](https://cloud.githubusercontent.com/assets/473101/7385317/218e31ac-ee11-11e4-9859-2633ca950d76.png)

**Comment by ikenfin** [comment]
Thanks! Fixed in 1.0.6 (but tested on Linux machine only)

**Comment by gj1118** [comment]
Works on my Mac too!!!
