### ISSUE TITLE
Icons for Symbolic Link Folders

### ISSUE THREAD

**Issue by daltones** [ikenfin/Sublime-Numix-light-theme#7]
I don't know exactly why, but when you have a symbolic link folder sometimes Sublime shows a regular folder and sometimes it shows a specific icon. Like this:

![symfolder](https://cloud.githubusercontent.com/assets/5603632/7423462/c243539c-ef6b-11e4-8ae3-63255ff8f426.png)

I looked into Sublime's default theme and there's this "icon_folder_dup" besides "icon_folder". That's all. So a new icon of a folder with an arrow would be great. =)

Btw, I'm very thankful. Great job on this theme!

**Comment by ikenfin** [comment]
Hi! Added this icon in 1.0.7, thanks!
