### ISSUE TITLE
no such prop

### ISSUE THREAD

**Issue by simonhaenisch** [ikenfin/Sublime-Numix-light-theme#8]
While hovering the sidebar, I get a message spammed into the console:

```
no such prop color
```

When hovering the tab bar, I get:

```
no such prop margin
no such prop layer1.outer_margin
```

And when hovering the little arrows on the left or on the right of the tab bar, I get:

```
no such prop height
no such prop layer0.outer_margin
```

It's kind of disrupting when working with the console... but this theme is the best one (I checked them all out) in combination with the Solarized Light scheme, so I hope you have the time to fix this @ikenfin :)

**Comment by ikenfin** [comment]
Thanks for feedback, i will fix this asap!

**Comment by ikenfin** [comment]
I have updated version, so i think it will appear in the package manager for a couple of days.
