### ISSUE TITLE
Find in Files panel behind status bar

### ISSUE THREAD

**Issue by simonhaenisch** [ikenfin/Sublime-Numix-light-theme#9]
In ST3103 the Find in Files panel is behind the status bar:

![capture](https://cloud.githubusercontent.com/assets/3410759/15151660/646ed298-16d2-11e6-8a68-d338c332e670.PNG)

There is a similar bug in this theme: https://github.com/equinusocio/material-theme#known-issues

I don't use the SidebarEnhancements plugin. For me it only happens for the Find in Files panel, all the other panels are shown correctly.

Making the panel higher is a quick fix, so this isn't a major issue.

**Comment by simonhaenisch** [comment]
I just realized that when I make the panel higher, it is moved to the right position and now it works as expected... so maybe this was just an issue because I had other themes installed before.

**Comment by marsberrys** [comment]
How to making the panel higher? I have the same problem

**Comment by marsberrys** [comment]
O, I read the link in your answer and solve the problem,thx~
